name: SteamHandler
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
#author: jadedResearcher <email@example.com>

environment:
  sdk: '>=2.1.0'

dependencies:
  args:
  shelf:
  http:

#dev_dependencies:
#  test: ^0.12.0
